site_name: Spider Documentation
pages:
- Home: index.md
- Getting Started: getting-started.md
- Responses: responses.md
- Command Builder: command-builder.md
- Models: models.md
- Advanced Usage: advanced.md
- Creating a Driver: create-driver.md
- Contributing: contributing.md